name: Deploy Turtle to DigitalOcean

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          debug: true
          script: |
            cd ..
            pm2 stop 0
            cd /check-valet/www/
            git pull origin staging
            cd ..
            pm2 restart 0